Added normal mapping example
webgpu/webgpu-samples pull request #305
Opened 2023-10-18 02:33 UTC by cmhhelgeson

An example of normal mapping that allows the user to adjust the lighting of the scene, the depth layers, and the currently displayed combination of diffuse, normal, and height maps (Spiral, Toybox, Bark).

Current issues to be addressed:
Parallax Occlusion Mapping (Possibly in a later PR)
Weird Bark Height Map Behavior
Creating Generalized Way of Loading Images in Assets Folder from Helper Functions Rather Than Public
Removing unused types, interfaces, and helper functions per usual.

2023-10-19 22:55 UTC, cmhhelgeson commented
Ready for review. Contains some of the same utils as used in the bitonicSort shader, which can either be inlined, kept, or moved to a separate folder depending on the maintainers' preferences.

2023-10-26 00:06 UTC, cmhhelgeson commented
Adding video to demonstrate intended functionality.

https://github.com/webgpu/webgpu-samples/assets/62450112/116be3a4-b037-46ac-84a9-aac80b4edd0e

2023-10-26 00:13 UTC, austinEng commented
@greggman could you help review this PR?

2023-10-26 10:29 UTC, greggman requested changes
So I don't know how opinionated to be on this review. Please excuse me if I'm being too strict. I'm just going with my own thoughts. I'm also unfamiliar with the other samples. They may have similar issues.

I ran it locally and ran into the following issues

* The cube is too far away to see any details

To fix I set the camera to this

```js
    cameraPosX: 0.0,
    cameraPosY: 0.8,   // was 0
    cameraPosZ: -1.4,  // was -2.4
```

I removed the x rotation from the cube since just moving the camera above the cube seemed less surprising

```js
    // mat4.rotateX(modelMatrix, 10, modelMatrix);
```

and updated the perspective to 0.1 instead of 1 for near

```js
  const projectionMatrix = mat4.perspective(
    (2 * Math.PI) / 5,
    aspect,
    0.1,   // was 1
    10.0   // was 100
  ) as Float32Array;
```

* The view matrix seemed wrong. I changed to this

```js
  function getViewMatrix() {
    return mat4.lookAt(
      [settings.cameraPosX, settings.cameraPosY, settings.cameraPosZ],
      [0, 0, 0],
      [0, 1, 0]
    );
  }
```

* The light seemed wrong. 

If the cube is at 0,0,0 and the camera is -Z then a light at

```js
    lightPosX: 1.7,
    lightPosY: -0.7,
    lightPosZ: 1.9,
```

Would be behind the cube (camera is -Z, light is +Z), to right (X is positive), and under the cube (Y is negative).

Changed to

```js
    lightPosX: 1.7,
    lightPosY: 0.7,   // above the cube
    lightPosZ: -1.9,  // same side as camera
```

* Then, I couldn't see any difference in rendering between these "Bump Mode"s

    | 'Normal Texture'
    | 'Depth Texture'
    | 'Normal Map'
    | 'Parallax Scale'
    | 'Steep Parallax';

To make sure I wasn't crazy I added an 'animate' GUI setting that stops the rotation. To do that I added a clock

```js
  const settings: GUISettings = {
    ...
    animate: true,
    ...
  };

  ...

  gui.add(settings, 'animate');

  ...

  let then = 0;
  let time = 0;
  function frame(now) {
    if (!pageState.active) return;

    const elapsedTime = settings.animate ? (then - now) * 0.001 : 0;
    time += elapsedTime;
    then = now;

    // Write to normal map shader
    const viewMatrix = getViewMatrix();
    const modelMatrix = getModelMatrix(time);
```

and updated `getModelMatrix` to

```js

  function getModelMatrix(time: number) {
    const modelMatrix = mat4.create();
    mat4.identitåy(modelMatrix);
    mat4.rotateY(modelMatrix, time * -0.5, modelMatrix);
    return modelMatrix;
  }
```

Once I had that in I tried stopping the animation and switching the bump mode. There is no difference in rendering between any of them except for "Diffuse Texture"


https://github.com/webgpu/webgpu-samples/assets/234804/11de13f4-cc3a-4e83-b3f1-5167eb252285

* I'm not sure why all the casts like this

```js
    // Write to normal map shader
    const viewMatrixTemp = getViewMatrix();
    const viewMatrix = viewMatrixTemp as Float32Array;

    const modelMatrixTemp = getModelMatrix();
    const modelMatrix = modelMatrixTemp as Float32Array;
```

I changed to 

```js
    // Write to normal map shader
    const viewMatrix = getViewMatrix();
    const modelMatrix = getModelMatrix(time);
```

And I don't get any TypeScript warnings 🤷‍♂️

Here's the changes I made mentioned above

https://github.com/greggman/webgpu-samples/commit/db27f546eb7ddb2346e00276127bfe79075ba6d1

2023-10-26 10:29 UTC, greggman commented on src/sample/normalMap/normalMap.wgsl
> +fn transpose3x3(mat: mat3x3f) -> mat3x3f  {
`transpose` is a built in WGSL function.

2023-10-26 10:29 UTC, greggman commented on src/sample/normalMap/normalMap.wgsl
> +  if (mapInfo.mappingType == 4) {
Are uber shaders generally considered bad practice? Would this be better with a separate shader for each mode? I'd think we don't want people copying this example if it's not considered a good thing to do. But I might wrong.

2023-10-26 10:29 UTC, greggman commented on src/sample/normalMap/normalMap.wgsl
> +  var depthPerLayer: f32 = 1.0 / f32(mapInfo.depthLayers);
Should you use `let` for things that never change, instead of `var`?

2023-10-26 10:29 UTC, greggman commented on src/sample/normalMap/normalMap.wgsl
> +  var delta_uv: vec2<f32> = viewDirTS.xy * depthScale / (viewDirTS.z * mapInfo.depthLayers);
you don't generally need to specify types on variables as they inherit their type from the type on the right. Here and a bunch of other places would it be better to just infer the types? It seems inconsistent where some places they are inferred and others not?

2023-10-26 10:29 UTC, greggman commented on src/sample/normalMap/utils.ts
> +    const layoutEntry: any = {};
This section can be changed to this to remove the `any`

```js
  for (let i = 0; i < bindings.length; i++) {
    layoutEntries.push({
      binding: bindings[i],
      visibility: visibilities[i % visibilities.length],
      [resourceTypes[i]]: resourceLayouts[i],
    });
  }
```

2023-10-26 10:29 UTC, greggman commented on src/sample/normalMap/utils.ts
> +      const groupEntry: any = {};
same as above

2023-10-26 10:29 UTC, greggman commented on src/meshes/box.ts
> +  tangents.fill(vec3.create(0.0, 0.0, 0.0));
I'm not sure this is doing what you think it's doing. It's making a single `vec3` and putting a reference to it in every slot of the array.

In other words, then this is done, 

```
tangents[12][0] = 456;
console.log(tangents[47][0]); // prints 456 
```

Is that what you wanted?

Also, there's no good reason to call `vec3.create(0.0, 0.0, 0.0)`. You can just do `vec3.create()` or better just `[0, 0, 0]`. It will be much faster, here and other places.

2023-10-26 10:29 UTC, greggman commented on src/sample/normalMap/main.ts
> +  const devicePixelRatio = window.devicePixelRatio || 1;
there's no need for the `|| 1`.  That's left over from like 2011. No browser the supports WebGPU would not have `devicePixelRatio`

2023-10-26 10:29 UTC, greggman commented on src/sample/normalMap/main.ts
> +  const liFunctionElements = document.getElementsByClassName('cr function');
Hacking deep into the GUI library's elements is brittle. This should probably be removed.

2023-10-26 16:38 UTC, cmhhelgeson commented on src/sample/normalMap/normalMap.wgsl
> +fn transpose3x3(mat: mat3x3f) -> mat3x3f  {
Fixed

2023-10-26 16:40 UTC, cmhhelgeson commented on src/meshes/box.ts
> +  console.log(indicesArray);
Removed.

2023-10-26 16:48 UTC, cmhhelgeson commented on src/meshes/box.ts
> +  tangents.fill(vec3.create(0.0, 0.0, 0.0));
Fixed

2023-10-26 16:48 UTC, cmhhelgeson commented on src/meshes/box.ts
> +    const tangent = vec3.fromValues(
Fixed

2023-10-26 17:09 UTC, cmhhelgeson commented on src/components/SampleLayout.module.css
Removed

2023-10-26 17:14 UTC, cmhhelgeson commented on src/sample/normalMap/utils.ts
> +      const groupEntry: any = {};
Fixed

2023-10-26 17:14 UTC, cmhhelgeson commented on src/sample/normalMap/utils.ts
> +    const layoutEntry: any = {};
Fixed

2023-10-26 17:14 UTC, cmhhelgeson commented on src/sample/normalMap/normalMap.wgsl
> +  var delta_uv: vec2<f32> = viewDirTS.xy * depthScale / (viewDirTS.z * mapInfo.depthLayers);
Made this consistent by removing type references when unecessary.

2023-10-26 17:18 UTC, cmhhelgeson commented on src/sample/normalMap/normalMap.wgsl
> +  if (mapInfo.mappingType == 4) {
I think it's more understandable and performant than having to manage multiple pipelines, especially when different types of depth mapping are still using the same code, but I defer to your expertise.

2023-10-26 17:19 UTC, cmhhelgeson commented on src/sample/normalMap/main.ts
> +  const liFunctionElements = document.getElementsByClassName('cr function');
I'll remove it, but we'd also have to remove it from bitonicSort as well.

2023-10-26 18:01 UTC, cmhhelgeson commented on src/sample/normalMap/normalMap.wgsl
> +  var depthPerLayer: f32 = 1.0 / f32(mapInfo.depthLayers);
Fixed

2023-10-26 18:27 UTC, cmhhelgeson commented
I implemented most of the suggestions (although the perspective of my camera doesn't seem to match yours). However, I left in the model rotation, since I think it more effectively demonstrates how the perceptual depth changes as the surface moves in and out of light, and I wasn't sure what was meant by surprising (too visually distracting, unexpected?).

2023-10-26 18:28 UTC, cmhhelgeson commented
Also, I was able to fix the issue with the map mode not changing by remembering to write that value as a u32 rather than a f32.

2023-10-27 00:47 UTC, greggman commented on src/sample/normalMap/main.ts
> +  const devicePixelRatio = window.devicePixelRatio || 1;
I will fix the other samples. Thanks for pointing that out.

2023-10-27 04:01 UTC, greggman approved these changes
lgtm

2023-10-27 04:01 UTC, merged