Fix image loading in normalMap sample
webgpu/webgpu-samples pull request #310
Opened 2023-10-27 18:24 UTC by cmhhelgeson

Get the image loading in the normalMap sample to actually work.

2023-10-27 19:05 UTC, cmhhelgeson commented
How are assets provided to the static build of the Next project? Adding images to assets and then running build or export doesn't seem to add them to either the static build or the out build.

2023-10-27 19:33 UTC, cmhhelgeson commented
Got rid of any utils outside of the main function that handled loading images. I also put all the images back in the assets folder. For some reason, the .next folder and out folder only build in the assets as part of the website when the images are referenced in main? Not sure why that might be. Regardless, image loading should be fixed after this next commit.

2023-10-28 16:01 UTC, cmhhelgeson commented
This should probably be addressed as soon as possible, the current example on the website is nonfunctional.

2023-10-28 23:26 UTC, greggman requested changes

2023-10-28 23:26 UTC, greggman commented on next.config.js
> +  eslint: {
remove?

2023-10-28 23:26 UTC, greggman commented on src/sample/normalMap/main.ts
> +    mat4.rotateX(modelMatrix, 0, modelMatrix);
why rotate by 0? remove?

2023-10-28 23:26 UTC, greggman commented on src/sample/texturedCube/main.ts
> +    const url = new URL(
why is this changed? revert?

2023-10-29 18:39 UTC, cmhhelgeson commented on src/sample/normalMap/main.ts
> +    mat4.rotateX(modelMatrix, 0, modelMatrix);
Fixed

2023-10-29 18:43 UTC, cmhhelgeson commented on next.config.js
> +  eslint: {
Removed

2023-10-29 22:52 UTC, greggman approved these changes

2023-10-29 23:41 UTC, merged