Remove entryPoint if not required
webgpu/webgpu-samples pull request #334
Opened 2023-11-27 13:27 UTC by beaufortfrancois

See https://github.com/gpuweb/gpuweb/pull/4387/

⚠️ Do not merge this PR until Chrome 121 reaches stable channel.

2023-11-27 15:15 UTC, Kangz commented
FYI @jimblandy @mwyrzykowski this will simplify samples a bit but will require entryPoint name defaulting.

2023-11-27 15:59 UTC, mwyrzykowski approved these changes

2023-11-28 02:42 UTC, kainino0x commented
Converting to draft to make the PR harder to accidentally merge.

2024-01-25 08:39 UTC, beaufortfrancois commented
We can now merge it as Chrome 121 is stable.

2024-01-25 17:16 UTC, austinEng approved these changes

2024-01-25 17:38 UTC, mwyrzykowski approved these changes

2024-01-26 00:45 UTC, greggman commented
ps: Firefox still requires entryPoint as of nightly 124.0a1 (2024-01-25) (64-bit)

@kdashg @jimblandy

2024-01-26 02:07 UTC, kdashg requested changes
Just a sec!

2024-01-26 16:55 UTC, jimblandy commented
So, we agree this is a sweet readability hack, and would like to see it deployed in the examples - but since it will break Firefox, we would like to wait to merge this PR until https://github.com/gfx-rs/wgpu/issues/5145 is closed.

2024-01-30 17:51 UTC, jimblandy commented
Note that we need both https://github.com/gfx-rs/wgpu/issues/5145 (the `wgpu`-side work) and Bugzilla [Bug 1877488](https://bugzilla.mozilla.org/show_bug.cgi?id=1877488) (the Firefox bindings work) fixed before Firefox will be able to handle omitted entry point names. @erichdongubler is actively working on these.

2024-03-06 07:50 UTC, beaufortfrancois commented
Firefox Nightly now handles omitted entry point names (I've checked locally). 
Since Safari Tech Preview and Chrome also handle them properly, I believe we can now merge this PR.

Note that I've just rebased it due to merging conflicts.

2024-03-06 13:28 UTC, ErichDonGubler commented
As the person who worked on this support in Firefox, I'm excited to see this land. 😁

2024-03-06 14:03 UTC, Kangz approved these changes

2024-03-07 12:43 UTC, beaufortfrancois commented
I've had to update the PR again. Please review and merge ;)

2024-03-07 12:55 UTC, ben-clayton commented on package-lock.json
Are the changes to `package-lock.json` intentional?

2024-03-07 12:59 UTC, beaufortfrancois commented on package-lock.json
Yes. They are due to me running `npm i` because of iframe changes.

2024-03-07 13:18 UTC, beaufortfrancois commented on package-lock.json
You're right. I'll revert package-lock.json changes then to not pollute this PR.

2024-03-07 13:21 UTC, beaufortfrancois commented on package-lock.json
Done

2024-03-08 06:36 UTC, beaufortfrancois commented
@kainino0x Can you merge?

2024-03-08 06:39 UTC, greggman commented
I'll merge

2024-03-08 06:41 UTC, merged